 let Frase = prompt("ingrese una Frase")
 let largofrase = Frase.length
 let contador_a = 0
 let contador_e = 0
 let contador_i = 0
 let contador_o = 0
 let contador_u = 0


// for (let index = 0; index < largofrase; index++) {
//     const element = Frase.toLowerCase().charAt(index)
//     if (element==="a"){
//         contador_a=contador_a+1
//     }   
        
//      else if (element==="e") {
//         contador_e=contador_e+1        
//     }
//     else if (element==="i") {
//         contador_i=contador_i+1        
//     }
//     else if (element==="o") {
//         contador_o=contador_o+1        
//     }
//     else if (element==="u") {
//         contador_u=contador_u+1        
//     }
    
// }
// document.write("<br> Cantidad de vocales e es="+contador_e)
// document.write("<br> Cantidad de vocales i es="+contador_i)
// document.write("<br> Cantidad de vocales o es="+contador_o)
// document.write("<br> Cantidad de vocales u es="+contador_u)
// document.write("<br> Cantidad de vocales a es="+contador_a)

// ota forma para contar el lugar de la primera vocal seria:

// for (let index = 0; index < largofrase; index++) {
//      const element = Frase.toLowerCase().charAt(index)
//      if (element==="a"||element==="e"||element==="i"||element==="o"||element==="u" ){
//         return document.write(index)
        
//      }   
     
        
//  }

// ota forma para contar el lugar de la primera vocal seria:

//  for (let index = 0; index < largofrase; index++) {
//     const element = Frase.toLowerCase().charAt(index)
//     if (element==="a"||element==="e"||element==="i"||element==="o"||element==="u" ){
//        document.write(index)
//        break
       
//     }   
    
       
// }